### ISSUE TITLE
更换链接

### ISSUE THREAD

**Issue by ghost** [imgblz/MisakaToolbox#2]
```
wget -N https://cdn.jsdelivr.net/gh/fscarmen/warp/menu.sh && bash menu.sh
```

这个 fscarmen warp 链接请用 raw 链
这个 cdn 链里的内容超级旧，会导致失败

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by imgblz** [comment]
准备自建CDN，目前先退回之前版本

**Comment by imgblz** [comment]
jsdelivr改为ghraw.imgblz.cn
